name: alteredbuilder

services:
  db:
    image: postgres:15.4-alpine
    volumes:
    - ./data/db:/var/lib/postgresql/data
    environment: &db_credentials
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 2s
      start_interval: 3s
  web:
    build: ./alteredbuilder
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./alteredbuilder:/code
    ports:
    - 8000:8000
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G