# Generated by Django 5.0.7 on 2024-07-24 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0034_create_promo_set"),
        ("trends", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("day_count", models.PositiveIntegerField(default=7)),
                ("date", models.DateField()),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decks.hero"
                    ),
                ),
            ],
        ),
    ]
