# Generated by Django 5.0.7 on 2024-07-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0034_create_promo_set"),
        ("trends", "0002_herotrend"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faction",
                    models.CharField(
                        choices=[
                            ("AX", "axiom"),
                            ("BR", "bravos"),
                            ("LY", "lyra"),
                            ("MU", "muna"),
                            ("OR", "ordis"),
                            ("YZ", "yzmir"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("ranking", models.PositiveIntegerField(default=0)),
                ("count", models.PositiveIntegerField(default=0)),
                ("day_count", models.PositiveIntegerField(default=7)),
                ("date", models.DateField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decks.card"
                    ),
                ),
            ],
        ),
    ]
