# Generated by Django 5.0.7 on 2024-07-25 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0034_create_promo_set"),
        ("trends", "0003_cardtrend"), 
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardtrend",
            name="count",
        ),
        migrations.AddField(
            model_name="cardtrend",
            name="hero",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hero_trend",
                to="decks.card",
            ),
        ),
    ]
