# Generated by Django 5.0.7 on 2024-07-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0005_alter_cardtrend_faction_alter_cardtrend_hero"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cardtrend",
            options={"ordering": ["-date", "-hero", "-faction", "ranking"]},
        ),
        migrations.AlterModelOptions(
            name="factiontrend",
            options={"ordering": ["-date", "-count"]},
        ),
        migrations.AlterModelOptions(
            name="herotrend",
            options={"ordering": ["-date", "-count"]},
        ),
    ]
