# Generated by Django 5.0.7 on 2024-07-31 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0044_delete_hero_temp"),
        ("trends", "0006_alter_cardtrend_options_alter_factiontrend_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herotrend",
            name="hero",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="decks.card"
            ),
        ),
    ]
