# Generated by Django 5.0.8 on 2024-08-31 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0058_card_created_at"),
        ("trends", "0007_alter_herotrend_hero"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeckTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AX", "axiom"),
                            ("BR", "bravos"),
                            ("LY", "lyra"),
                            ("MU", "muna"),
                            ("OR", "ordis"),
                            ("YZ", "yzmir"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("ranking", models.PositiveIntegerField(default=0)),
                ("day_count", models.PositiveIntegerField(default=7)),
                ("date", models.DateField()),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decks.deck"
                    ),
                ),
                (
                    "hero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deck_trend",
                        to="decks.card",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-hero", "-faction", "ranking"],
            },
        ),
    ]
