# Generated by Django 5.0.8 on 2024-08-31 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0058_card_created_at"),
        ("trends", "0008_decktrend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decktrend",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trend",
                to="decks.deck",
            ),
        ),
    ]
