# Generated by Django 5.0.14 on 2025-06-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0010_usertrend"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertrend",
            options={"ordering": ["-date", "count"]},
        ),
        migrations.RenameField(
            model_name="usertrend",
            old_name="ranking",
            new_name="count",
        ),
    ]
