# Generated by Django 5.0.14 on 2025-06-02 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0011_alter_usertrend_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertrend",
            options={"ordering": ["-date", "-count"]},
        ),
    ]
