# Generated by Django 5.0.8 on 2024-08-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(choices=[("comment", "Comment")]),
        ),
    ]
