# Generated by Django 5.0.8 on 2024-08-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notification_verb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("deck", "Deck"),
                    ("follow", "Follow"),
                    ("love", "Love"),
                ]
            ),
        ),
    ]
