# Generated by Django 5.0.13 on 2025-03-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("decks", "0074_set_release_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_id", models.IntegerField(unique=True)),
                ("name", models.CharField()),
                ("player_count", models.IntegerField()),
                ("date", models.DateField()),
                ("location", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="TrainedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faction",
                    models.CharField(
                        choices=[
                            ("AX", "axiom"),
                            ("BR", "bravos"),
                            ("LY", "lyra"),
                            ("MU", "muna"),
                            ("OR", "ordis"),
                            ("YZ", "yzmir"),
                        ],
                        max_length=2,
                    ),
                ),
                ("model_data", models.BinaryField()),
                ("active", models.BooleanField(default=False)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TournamentDeck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_id", models.IntegerField()),
                ("player", models.CharField()),
                ("placement", models.IntegerField()),
                ("cards", models.JSONField()),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="decks.card"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recommender.tournament",
                    ),
                ),
            ],
        ),
    ]
