# Generated by Django 5.0.13 on 2025-03-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainedmodel",
            name="name",
            field=models.CharField(default="logistic regression"),
            preserve_default=False,
        ),
    ]
