# Generated by Django 5.0.13 on 2025-03-30 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0003_rename_name_trainedmodel_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentdeck",
            name="tournament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recommender.tournament",
            ),
        ),
    ]
