# Generated by Django 5.0.14 on 2025-04-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0004_alter_tournamentdeck_tournament"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainedmodel",
            options={
                "permissions": [("can_use_recommender", "Can use deck recommender")]
            },
        ),
    ]
