# Generated by Django 5.0.14 on 2025-04-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0005_alter_trainedmodel_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournamentdeck",
            old_name="remote_id",
            new_name="player_id",
        ),
    ]
