# Generated by Django 5.0.14 on 2025-09-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0006_rename_remote_id_tournamentdeck_player_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="player_count",
            field=models.IntegerField(null=True),
        ),
    ]
