# Generated by Django 5.0.14 on 2025-09-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("rss", "RSS"),
                            ("youtube", "YouTube"),
                            ("twitch", "Twitch"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255, null=True)),
                ("site", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("description", models.TextField(blank=True)),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("published_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
