# Generated by Django 5.0.3 on 2024-03-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0002_import_altered_cards"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hero",
            options={"verbose_name_plural": "heroes"},
        ),
    ]
