# Generated by Django 5.0.3 on 2024-03-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0004_deck_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
