# Generated by Django 5.0.3 on 2024-03-04 16:32
import os
from pathlib import Path

from django.contrib.auth.models import User
from django.db import migrations

from decks.views import create_new_deck


def import_deck(file):
    user = User.objects.get(username="admin")
    with open(file, "r") as deck_file:
        decklist = deck_file.read()

    create_new_deck(user, {
        "name": file.name,
        "decklist": decklist,
        "is_public": True
    })


def create_starter_decks(apps, schema_editor):
    stater_decks_dir = Path(__file__).resolve().parent / "starter-decks"
    
    for file in os.listdir(stater_decks_dir):
        import_deck(stater_decks_dir / file)


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0006_deck_created_at_deck_modified_at"),
    ]

    operations = [migrations.RunPython(create_starter_decks)]
