# Generated by Django 5.0.3 on 2024-04-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0007_create_starter_decks"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
