# Generated by Django 5.0.3 on 2024-04-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0009_deck_is_standard_legal"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="standard_legality_errors",
            field=models.JSONField(default=list),
        ),
    ]
