# Generated by Django 5.0.3 on 2024-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0010_deck_standard_legality_errors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="is_standard_legal",
            field=models.BooleanField(null=True),
        ),
    ]
