# Generated by Django 5.0.3 on 2024-04-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0012_deck_draft_legality_errors_deck_is_draft_legal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="draft_legality_errors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="deck",
            name="standard_legality_errors",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
