# Generated by Django 5.0.3 on 2024-05-23 20:24

from django.db import migrations

from decks.models import Deck
from decks.game_modes import update_deck_legality


def force_update_legality(apps, schema_editor):
    decks = Deck.objects.all()

    for deck in decks:
        original_standard_legality = deck.standard_legality_errors
        original_draft_legality = deck.draft_legality_errors
        update_deck_legality(deck)
        if (
            original_standard_legality != deck.standard_legality_errors
            or original_draft_legality != deck.draft_legality_errors
        ):
            print(f"Updated legality of deck: {deck}")
            deck.save(
                update_fields=[
                    "is_standard_legal",
                    "standard_legality_errors",
                    "is_draft_legal",
                    "draft_legality_errors",
                ]
            )


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0014_alter_card_reference"),
    ]

    operations = [migrations.RunPython(force_update_legality)]
