# Generated by Django 5.0.3 on 2024-06-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0019_deck_decks_deck_modifie_f6692c_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="image_url_de",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="image_url_it",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="name_de",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="name_it",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="echo_effect_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="echo_effect_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="main_effect_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="main_effect_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hero",
            name="main_effect_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hero",
            name="main_effect_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permanent",
            name="echo_effect_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permanent",
            name="echo_effect_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permanent",
            name="main_effect_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permanent",
            name="main_effect_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spell",
            name="echo_effect_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spell",
            name="echo_effect_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spell",
            name="main_effect_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spell",
            name="main_effect_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deck",
            name="description",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
