# Generated by Django 5.0.3 on 2024-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0020_card_image_url_de_card_image_url_it_card_name_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="name",
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name="card",
            name="name_de",
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="name_en",
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="name_es",
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="name_fr",
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="name_it",
            field=models.CharField(max_length=48, null=True),
        ),
    ]
