# Generated by Django 5.0.3 on 2024-07-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0022_privatelink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatelink",
            name="last_accessed",
        ),
        migrations.AddField(
            model_name="privatelink",
            name="last_accessed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
