# Generated by Django 5.0.3 on 2024-07-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0023_remove_privatelink_last_accessed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatelink",
            name="last_accessed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
