# Generated by Django 5.0.3 on 2024-07-02 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0024_alter_privatelink_last_accessed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatelink",
            name="deck",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="decks.deck"
            ),
        ),
    ]
