# Generated by Django 5.0.3 on 2024-07-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0025_alter_privatelink_deck"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deck",
            options={"ordering": ["-modified_at"]},
        ),
    ]
