# Generated by Django 5.0.3 on 2024-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0026_alter_deck_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="is_exalts_legal",
            field=models.BooleanField(null=True),
        ),
    ]
