# Generated by Django 5.0.3 on 2024-07-18 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0028_force_update_legality"),
    ]

    operations = [
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("code", models.CharField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="lovepoint",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="privatelink",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="card",
            name="type",
            field=models.CharField(
                choices=[
                    ("spell", "Spell"),
                    ("permanent", "Permanent"),
                    ("token", "Token"),
                    ("character", "Character"),
                    ("hero", "Hero"),
                    ("token_mana", "Token Mana"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="set",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="decks.set"
            ),
        ),
    ]
