# Generated by Django 5.0.3 on 2024-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0029_set_alter_lovepoint_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="reference_code",
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="set",
            name="short_name",
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="set",
            name="code",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
