# Generated by Django 5.0.3 on 2024-07-18 12:40

from django.db import migrations


def init_models(apps):
    global Card, Set
    Card = apps.get_model("decks", "Card")
    Set = apps.get_model("decks", "Set")


def create_sets(apps, schema_editor):
    init_models(apps)

    Set.objects.update_or_create(
        name="Beyond The Gates", short_name="BTG", code="CORE", reference_code="_CORE_"
    )
    Set.objects.update_or_create(
        name="Kickstarter Edition",
        short_name="BTG-KS",
        code="COREKS",
        reference_code="_COREKS_",
    )


def link_cards_to_sets(apps, schema_editor):

    card_sets = Set.objects.all()

    for card_set in card_sets:
        Card.objects.filter(reference__contains=card_set.reference_code).update(
            set=card_set
        )


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0030_set_reference_code_set_short_name_alter_set_code"),
    ]

    operations = [
        migrations.RunPython(create_sets),
        migrations.RunPython(link_cards_to_sets),
    ]
