# Generated by Django 5.0.3 on 2024-07-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0032_create_sets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="description",
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
