# Generated by Django 5.0.7 on 2024-07-30 10:24

from django.conf import settings
from django.db import migrations
from django.utils.translation import activate


def init_models(apps):
    global Card
    Card = apps.get_model("decks", "Card")


def refactor_cards(apps, schema_editor):
    init_models(apps)

    for card in Card.objects.all():
        match card.type:
            case "hero":
                refactor_hero(card)
            case "spell":
                refactor_spell(card)
            case "permanent":
                refactor_permanent(card)
            case "character":
                refactor_character(card)
            case _:
                print(f"un-typed card found: {card}")


def refactor_hero(card):
    card.stats = {
        "reserve_count": card.hero.reserve_count,
        "permanent_count": card.hero.permanent_count,
    }
    for language, _ in settings.LANGUAGES:
        setattr(card, f"main_effect_temp_{language}", getattr(card.hero, f"main_effect_{language}"))
    card.save()


def refactor_spell(card):
    card.stats = {
        "main_cost": card.spell.main_cost,
        "recall_cost": card.spell.recall_cost,
    }
    for language, _ in settings.LANGUAGES:
        setattr(card, f"main_effect_temp_{language}", getattr(card.spell, f"main_effect_{language}"))
        setattr(card, f"echo_effect_temp_{language}", getattr(card.spell, f"echo_effect_{language}"))
    card.save()


def refactor_permanent(card):
    card.stats = {
        "main_cost": card.permanent.main_cost,
        "recall_cost": card.permanent.recall_cost,
    }
    for language, _ in settings.LANGUAGES:
        setattr(card, f"main_effect_temp_{language}", getattr(card.permanent, f"main_effect_{language}"))
        setattr(card, f"echo_effect_temp_{language}", getattr(card.permanent, f"echo_effect_{language}"))
    card.save()


def refactor_character(card):
    card.stats = {
        "main_cost": card.character.main_cost,
        "recall_cost": card.character.recall_cost,
        "forest_power": card.character.forest_power,
        "mountain_power": card.character.mountain_power,
        "ocean_power": card.character.ocean_power,
    }
    for language, _ in settings.LANGUAGES:
        setattr(card, f"main_effect_temp_{language}", getattr(card.character, f"main_effect_{language}"))
        setattr(card, f"echo_effect_temp_{language}", getattr(card.character, f"echo_effect_{language}"))
    card.save()


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0038_card_echo_effect_temp_card_echo_effect_temp_de_and_more"),
    ]

    operations = [
        migrations.RunPython(refactor_cards)
    ]
