# Generated by Django 5.0.7 on 2024-07-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0047_restore_modified_at_of_decks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="card_ptr",
        ),
        migrations.RemoveField(
            model_name="hero",
            name="card_ptr",
        ),
        migrations.RemoveField(
            model_name="permanent",
            name="card_ptr",
        ),
        migrations.RemoveField(
            model_name="spell",
            name="card_ptr",
        ),
        migrations.DeleteModel(
            name="TempDeck",
        ),
        migrations.DeleteModel(
            name="Character",
        ),
        migrations.DeleteModel(
            name="Hero",
        ),
        migrations.DeleteModel(
            name="Permanent",
        ),
        migrations.DeleteModel(
            name="Spell",
        ),
    ]
