# Generated by Django 5.0.7 on 2024-08-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0053_migrate_heroes_to_promo_set"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subtype",
            options={"ordering": ["name"]},
        ),
    ]
