# Generated by Django 5.0.8 on 2024-08-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0056_delete_italian_image_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="decks.deck",
            ),
        ),
    ]
