# Generated by Django 5.0.8 on 2024-08-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0057_alter_comment_deck"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
