# Generated by Django 5.0.8 on 2024-08-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0058_card_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="deck",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="decks", to="decks.tag"
            ),
        ),
    ]
