# Generated by Django 5.0.9 on 2024-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0063_favoritecard"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["rarity"], name="decks_card_rarity_fefb3f_idx"),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["faction"], name="decks_card_faction_7948ca_idx"
            ),
        ),
    ]
