# Generated by Django 5.0.9 on 2025-01-11 17:39

from django.db import migrations, models


def init_models(apps):
    global Card
    Card = apps.get_model("decks", "Card")


def rename_choices(apps, schema_editor):
    init_models(apps)

    Card.objects.filter(type="permanent").update(type="landmark_permanent")


def undo_rename_choices(apps, schema_editor):
    init_models(apps)

    Card.objects.filter(type="landmark_permanent").update(type="permanent")


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0065_fix_stats_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="card",
            name="name_de",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="name_en",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="name_es",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="name_fr",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="name_it",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="reference",
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="card",
            name="subtypes",
            field=models.ManyToManyField(blank=True, to="decks.subtype"),
        ),
        migrations.AlterField(
            model_name="card",
            name="type",
            field=models.CharField(
                choices=[
                    ("spell", "Spell"),
                    ("landmark_permanent", "Landmark Permanent"),
                    ("expedition_permanent", "Expedition Permanent"),
                    ("token", "Token"),
                    ("character", "Character"),
                    ("hero", "Hero"),
                    ("token_mana", "Token Mana"),
                ]
            ),
        ),
        migrations.RunPython(rename_choices, reverse_code=undo_rename_choices),
    ]
