# Generated by Django 5.0.3 on 2024-07-18 12:40

from django.db import migrations


def init_models(apps):
    global Card, Set
    Card = apps.get_model("decks", "Card")
    Set = apps.get_model("decks", "Set")


def create_set(apps, schema_editor):
    init_models(apps)

    Set.objects.update_or_create(
        name="Trial by Frost", short_name="TBF", code="ALIZE", reference_code="_ALIZE_"
    )


def delete_set(apps, schema_editor):
    init_models(apps)

    Set.objects.filter(code="ALIZE").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0066_alter_card_name_alter_card_name_de_and_more"),
    ]

    operations = [
        migrations.RunPython(create_set, reverse_code=delete_set),
    ]
