# Generated by Django 5.0.9 on 2025-01-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0067_add_alize_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="is_doubles_legal",
            field=models.BooleanField(null=True),
        ),
    ]
