# Generated by Django 5.0.11 on 2025-02-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0069_force_update_legality"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_alt_art",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="card",
            name="is_promo",
            field=models.BooleanField(default=False),
        ),
    ]
