# Generated by Django 5.0.13 on 2025-03-29 15:20

import datetime
from django.db import migrations, models


def init_models(apps):
    global Set
    Set = apps.get_model("decks", "Set")


def set_release_date(apps, schema_editor):
    init_models(apps)

    Set.objects.filter(code="CORE").update(release_date=datetime.date(2024, 9, 13))
    Set.objects.filter(code="COREKS").update(release_date=datetime.date(2024, 9, 13))
    Set.objects.filter(code="ALIZE").update(release_date=datetime.date(2025, 1, 31))


def empty_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0073_force_update_legality"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="release_date",
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.RunPython(set_release_date, reverse_code=empty_reverse),
    ]
