# Generated by Django 5.0.14 on 2025-04-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0074_set_release_date"),
        ("recommender", "0005_alter_trainedmodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="copy_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="DeckCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "copied_deck",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies_from",
                        to="decks.deck",
                    ),
                ),
                (
                    "source_deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies_to",
                        to="decks.deck",
                    ),
                ),
                (
                    "source_tournament_deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommender.tournamentdeck",
                    ),
                ),
            ],
        ),
    ]
