# Generated by Django 5.0.14 on 2025-04-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0075_deck_copy_count_deckcopy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deckcopy",
            old_name="copied_deck",
            new_name="target_deck",
        ),
    ]
