# Generated by Django 5.0.14 on 2025-05-04 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0076_rename_copied_deck_deckcopy_target_deck"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField(null=True)),
                ("count", models.PositiveIntegerField(default=1)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decks.card"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cardprice",
            constraint=models.UniqueConstraint(
                fields=("card", "date"), name="unique_card_date_price"
            ),
        ),
    ]
