# Generated by Django 5.0.14 on 2025-05-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0077_cardprice_cardprice_unique_card_date_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardprice",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="decks.card",
            ),
        ),
    ]
