# Generated by Django 5.0.14 on 2025-09-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0079_set_name_de_set_name_en_set_name_es_set_name_fr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="description",
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
