# Generated by Django 5.0.14 on 2025-09-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0080_alter_deck_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="display_image_url",
            field=models.URLField(blank=True),
        ),
    ]
