# Generated by Django 5.0.14 on 2025-09-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0081_card_display_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="is_main_set",
            field=models.BooleanField(default=False),
        ),
    ]
