# Generated by Django 5.0.14 on 2025-10-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0082_set_is_main_set"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                condition=models.Q(("is_alt_art", False), ("is_promo", False)),
                fields=["set", "rarity"],
                name="card_base_query_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="set",
            index=models.Index(
                condition=models.Q(("is_main_set", True)),
                fields=["id"],
                name="set_is_main_set_idx",
            ),
        ),
    ]
