# Generated by Django 5.1.13 on 2025-11-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0083_card_card_base_query_idx_set_set_is_main_set_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("C", "common"),
                    ("R", "rare"),
                    ("U", "unique"),
                    ("E", "exalted"),
                ],
                max_length=1,
            ),
        ),
    ]
