# Generated by Django 5.1.13 on 2026-01-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0084_alter_card_rarity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deck",
            old_name="is_exalts_legal",
            new_name="is_nuc_legal",
        ),
    ]
