# Generated by Django 5.1.13 on 2026-01-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0085_rename_is_exalts_legal_deck_is_nuc_legal"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="is_singleton_legal",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="deck",
            name="singleton_legality_errors",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
