# Generated by Django 5.1.13 on 2026-02-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0086_deck_is_singleton_legal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("family_name", models.CharField()),
                (
                    "faction",
                    models.CharField(
                        choices=[
                            ("AX", "axiom"),
                            ("BR", "bravos"),
                            ("LY", "lyra"),
                            ("MU", "muna"),
                            ("OR", "ordis"),
                            ("YZ", "yzmir"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="is_legal",
            field=models.BooleanField(default=True),
        ),
    ]
