# Generated by Django 5.0.8 on 2024-08-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="discord",
        ),
    ]
