# Generated by Django 5.0.8 on 2024-08-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="altered_handle",
            field=models.CharField(null=True),
        ),
    ]
