# Generated by Django 5.0.8 on 2024-08-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_userprofile_discord"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="discord_public",
            field=models.BooleanField(
                default=False, verbose_name="Show Discord Handle Publicly"
            ),
        ),
    ]
