# Generated by Django 5.0.8 on 2024-08-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_create_equinox_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="discord_public",
            field=models.BooleanField(default=False),
        ),
    ]
