# Generated by Django 5.0.8 on 2024-08-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_create_profiles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="follow",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
