# Generated by Django 5.0.9 on 2024-10-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_follow_options_alter_follow_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.CharField(default="DEFAULT.png"),
        ),
    ]
