# Generated by Django 5.0.14 on 2025-06-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="collection",
            field=models.CharField(null=True),
        ),
    ]
