# Generated by Django 5.0.14 on 2025-06-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_userprofile_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="collection",
            field=models.CharField(blank=True, null=True),
        ),
    ]
