# Generated by Django 5.1.13 on 2026-01-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_alter_userprofile_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_spam",
            field=models.BooleanField(default=False),
        ),
    ]
