name: Trends CICD

on:
  push:
    branches:
    - master
    paths:
    - "alteredbuilder/*/management/commands/*.py"
    - "alteredbuilder/config/commands.py"
    - ".github/workflows/commands_cicd.yml"

env:
  DEBUG: False
  USE_GCS_STATICS: False

defaults:
  run:
    working-directory: ./alteredbuilder

jobs:
  deploy:
    name: Deploy command '${{ matrix.command }}' to Cloud Run
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        command:
        - generate_trends
        - calculate_deck_legality
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Authenticate into GCP
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_GITHUB_SA_JSON }}
    - name: Prepare job name
      id: vars
      run: echo "JOB_NAME=${{ matrix.command }} | sed 's/_/-/g' >> $GITHUB_OUTPUT"
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        project_id: ${{ vars.GCP_PROJECT }}
        region: ${{ vars.REGION }}
        job: ${{ steps.vars.outputs.JOB_NAME }}
        image: ${{ secrets.AR_REPOSITORY }}/${{ vars.CLOUD_RUN_SERVICE_NAME }}
        flags: |
          --command=python
          --args manage.py,${{ matrix.command }}
          --set-cloudsql-instances=${{ secrets.CLOUD_SQL_INSTANCE }}
          --service-account=${{ secrets.CLOUD_RUN_SA_NAME }}
          --cpu=1000m
          --memory=512Mi