name: Django CI

on:
  push

env:
  RUN_ON: ubuntu-22.04
  DEBUG: False
  USE_GCS_STATICS: False

defaults:
  run:
    working-directory: ./alteredbuilder

jobs:
  build:
    runs-on: ${{ env.RUN_ON }}
    steps:
    - uses: actions/checkout@v4
    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_GITHUB_SA }}
    - uses: google-github-actions/setup-gcloud@v1
    - run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev --quiet
    - run: docker build . --tag ${{ vars.AR_REPOSITORY }}
    - run: docker push ${{ vars.AR_REPOSITORY }}
  test:
    needs: build
    runs-on: ${{ env.RUN_ON }}
    services:
      db:
        image: postgres:15.4
        ports:
        - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
      env:
        DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
  migrate:
    needs: test
    runs-on: ${{ env.RUN_ON }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Google Cloud SQL Auth Proxy
      uses: mattes/gce-cloudsql-proxy-action@v1
      with:
        creds: ${{ secrets.GCP_GITHUB_SA }}
        instance: ${{ vars.CLOUD_SQL_INSTANCE }}
        port: 5432
    - name: Run migrations
      run: |
        python manage.py migrate
      env:
        DATABASE_URL: ${{ secrets.MIGRATION_DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
