name: Django CICD

on:
  push
#   push:
#     branches:
#     - master
    # paths:
    # - "alteredbuilder/config/__init__.py"

defaults:
  run:
    working-directory: ./alteredbuilder

jobs:
  new_release:
    name: Create a new release
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Read file
      id: version_file
      uses: juliangruber/read-file-action@v1
      with:
        path: "./config/__init__.py"
    - name: Parse version
      id: version
      uses: actions-ecosystem/action-regex-match@v2
      with:
        text: ${{ steps.version_file.outputs.content }}
        regex: "__version__ = \"(.*)\""
    - run: echo "${{ steps.version.outputs.group1 }}"