name: Nginx CICD

on:
  push:
    branches:
    - master
    paths:
    - "nginx/**"
    - ".github/workflows/nginx_cicd.yml"

env:
  IMAGE_NAME: nginx

defaults:
  run:
    working-directory: ./nginx

jobs:
  build_and_push_image:
    name: Build and push the image
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Authenticate into GCP
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_GITHUB_SA }}
    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
    - name: Set up docker
      run: gcloud auth configure-docker ${{ vars.NGINX_REGION }}-docker.pkg.dev --quiet
    - name: Build image
      run: docker build . --tag ${{ vars.NGINX_AR_REPOSITORY }}/${{ env.IMAGE_NAME }}
    - name: Push image
      run: docker push ${{ vars.NGINX_AR_REPOSITORY }}/${{ env.IMAGE_NAME }}

  deploy:
    name: Deploy to Cloud Run
    needs: [build_and_push_image]
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Authenticate into GCP
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_GITHUB_SA }}
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        project_id: ${{ vars.GCP_PROJECT }}
        region: ${{ vars.NGINX_REGION }}
        service: ${{ vars.CLOUD_RUN_SERVICE_NAME }}
        image: ${{ vars.NGINX_AR_REPOSITORY }}/${{ env.IMAGE_NAME }}
        flags: |
          --platform=managed
          --port=8000
          --allow-unauthenticated
          --service-account=${{ vars.CLOUD_RUN_SA_NAME }}
          --cpu=1000m
          --memory=256Mi