name: Update card pool 

on:
  schedule:
  - cron: "0 19 * * 1-5"

env:
  DEBUG: False
  USE_GCS_STATICS: False

defaults:
  run:
    working-directory: ./alteredbuilder

jobs:
  update_card_pool:
    name: Update the card pool
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Configure Google Cloud SQL Auth Proxy
      uses: mattes/gce-cloudsql-proxy-action@v1
      with:
        creds: ${{ secrets.GCP_GITHUB_SA }}
        instance: ${{ vars.CLOUD_SQL_INSTANCE }}
        port: 5432
    - name: Update the card pool
      run: python manage.py update_card_pool
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_URL: ${{ secrets.MIGRATION_DATABASE_URL }}
